CREATE TABLE IF NOT EXISTS accounts(
    "id" SERIAL PRIMARY KEY UNIQUE,
    username VARCHAR(30) NOT NULL UNIQUE,
    "password" VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL,
    gender CHAR(1) CHECK (gender = 'M' or gender = 'F') NOT NULL,
    age INT NOT NULL,
    job_title VARCHAR(40) NOT NULL,
    ip VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS addresses(
    "id" SERIAL PRIMARY KEY UNIQUE,
    street VARCHAR(30) NOT NULL,
    town VARCHAR(30) NOT NULL,
    country VARCHAR(30) NOT NULL,
    account_id INT REFERENCES  accounts(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS photos(
    "id" SERIAL PRIMARY KEY UNIQUE,
    "description" TEXT,
    capture_date TIMESTAMP NOT NULL,
    views INT DEFAULT 0 CHECK (views >= 0) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments(
    "id" SERIAL PRIMARY KEY UNIQUE,
    content VARCHAR(255) NOT NULL,
    published_on TIMESTAMP NOT NULL,
    photo_id INT REFERENCES photos(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS accounts_photos(
    account_id INT REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
    photo_id INT REFERENCES photos(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
    PRIMARY KEY(account_id, photo_id)
);

CREATE TABLE IF NOT EXISTS likes(
    "id" SERIAL PRIMARY KEY UNIQUE,
    photo_id INT REFERENCES photos(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
    account_id INT REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
);